<?php include 'header.php';?>
<div class="row">
<p dir="ltr"><span>Nomful&rsquo;s Privacy Policy</span></p>
<p dir="ltr"><span>Protecting your privacy is really important to us. Accordingly, we&rsquo;re providing this Privacy Policy to explain our practices regarding the collection, use and disclosure of information that we receive when you use our Services (defined as the services included in &ldquo;Services&rdquo; as defined in both our </span><a href="http://nomful.com/terms.php"><span>Customer Terms of Service</span></a><span>. This Privacy Policy applies only to those websites, services and applications included within &ldquo;Services&rdquo; and doesn&rsquo;t apply to any third-party websites, services or applications, even if they are accessible through our Services. Also, please note that, unless we define a term in this Privacy Policy, all capitalized words used in this Privacy Policy have the same meanings as in our Terms of Service.</span></p>
<h3 dir="ltr"><span>How do we collect and use information?</span></h3>
<p dir="ltr"><span>Our primary goals in collecting information are to provide and improve our Services, to administer your use of the Services (including your Account or Coach Account, as applicable), and to enable you to enjoy and easily navigate our Services.</span></p>
<p dir="ltr"><span>Personal Information. When you create an Account or Coach Account we&rsquo;ll collect certain information that may include information that can be used to identify you, such as your name, email address and phone number (&ldquo;Personally Identifiable Information&rdquo; or &ldquo;PII&rdquo;). We may also collect certain information that is not PII because it cannot be used by itself to identify you, such as your gender, age, date of birth and zip code. We or our third party services providers may also collect certain information from you in connection with your use of the Services, including payment information.</span></p>
<p dir="ltr"><span>Information Collected Using Cookies. We collect certain information through the use of &ldquo;cookies,&rdquo; which are small text files that are saved by your browser when you access our Services. We may use both session cookies and persistent cookies to identify that you&rsquo;ve logged in to the Services and to tell us how and when you interact with our Services. We may also use cookies to monitor aggregate usage and web traffic routing on our Services and to customize and improve our Services. Unlike persistent cookies, session cookies are deleted when you log off from the Services and close your browser. Although most browsers automatically accept cookies, you can change your browser options to stop automatically accepting cookies or to prompt you before accepting cookies. Please note, however, that if you don&rsquo;t accept cookies, you may not be able to access all portions or features of the Services. Some third-party services providers that we engage (including third-party advertisers) may also place their own cookies on your browser. Note that this Privacy Policy covers only our use of cookies and does not include use of cookies by such third parties.</span></p>
<p dir="ltr"><span>Information Related to Use of the Services. Our servers automatically record certain information about how a person uses our Services (we refer to this information as &ldquo;Log Data&rdquo;), including both Account and Coach Account holders and non-account holders (&ldquo;Users&rdquo;). Log Data may include information such as a User&rsquo;s Internet Protocol (IP) address, device ID, browser type, operating system, the web page that a User was visiting before accessing our Services, the pages or features of our Services to which a User browsed and the time spent on those pages or features, search terms, the links on our Services that a User clicked on, interactions between a Customer and Coaches, diet history and habits, and Content that a Customer submits to the Services when logging eating habits in his or her food journal on the Services. We use this information to administer the Services and we analyze (and may engage third parties to analyze) this information to improve and enhance the Services by expanding their features and functionality and tailoring them to our Users&rsquo; needs and preferences. We may use a person&rsquo;s IP address to fight spam, malware and identity theft. We also use the IP Address to generate aggregate, non-identifying information about how our Services are used.</span></p>
<p dir="ltr"><span>Location Information. In some cases we collect and store information about where you are located, such as by converting your IP address or mobile GPS data into a rough geolocation. We may use location information to improve and personalize our Services for you.</span></p>
<h3 dir="ltr"><span>What Information Do We Share With Third Parties?</span></h3>
<p dir="ltr"><span>We will not share any PII that we have collected from you except as described below. &nbsp;Just to be clear, this paragraph also applies to any health-related information about you that we may collect through the Services.</span></p>
<p dir="ltr"><span>Information Shared with Our Services Providers. We may engage third party service providers, such as third party payment processors, to work with us to administer and provide the Services. These third-party services providers have access to your PII only for the purpose of performing services on our behalf.</span></p>
<p dir="ltr"><span>Information Shared with Third Parties. We may share aggregated information and non-identifying information with third parties for industry analysis, demographic profiling and other similar purposes.</span></p>
<p dir="ltr"><span>Information Disclosed in Connection with Business Transactions. Information that we collect from our users, including PII, is considered to be a business asset. As a result, if we go out of business or enter bankruptcy or if we are acquired as a result of a transaction such as a merger, acquisition or asset sale, your PII may be disclosed or transferred to the third-party acquirer in connection with the transaction.</span></p>
<p dir="ltr"><span>Information Disclosed for Our Protection and the Protection of Others. It is our policy to protect you from having your privacy violated through abuse of the legal systems, whether by individuals, entities or government, and to contest claims that we believe to be invalid under applicable law. However, it is also our policy to cooperate with government and law enforcement officials and private parties. Accordingly, we reserve the right to disclose any information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary: (i) to satisfy or comply with any applicable law, regulation or legal process or to respond to lawful requests, including subpoenas, warrants or court orders; (ii) to protect our property, rights and safety and the rights, property and safety of third parties or the public in general; and (iv) to prevent or stop activity we consider to be illegal or unethical.</span></p>
<h3 dir="ltr"><span>The Security of Your Information.</span></h3>
<p dir="ltr"><span>We take reasonable measures to protect the information that we collect from or about you (including your PII) from unauthorized access, use or disclosure. Please be aware, however, that no method of transmitting information over the Internet or storing information is completely secure. Accordingly, we cannot guarantee the absolute security of any information.</span></p>
<h3 dir="ltr"><span>Links to Other Sites.</span></h3>
<p dir="ltr"><span>Our Services may contain links to other websites and services. Any information that you provide on or to a third-party website or service is provided directly to the owner of the website or service and is subject to that party's privacy policy. Our Privacy Policy does not apply to such websites or services and we&rsquo;re not responsible for the content, privacy or security practices and policies of those websites or services. To protect your information we recommend that you carefully review the privacy policies of other websites and services that you access.</span></p>
<h3 dir="ltr"><span>Modifying Your Information.</span></h3>
<p dir="ltr"><span>If you want us to modify or delete your PII and your Account, please contact us at </span><a href="mailto:founders@nomful.com"><span>founders@nomful.com</span></a><span> with your request. We&rsquo;ll take steps to delete your information as soon as is practicable, but some information may remain in archived/backup copies for our records or as otherwise required by law.</span></p>
<h3 dir="ltr"><span>International Transfer.</span></h3>
<p dir="ltr"><span>Your PII may be transferred to, and maintained on, computers located outside of your state, province, country or other governmental jurisdiction where the privacy laws may not be as protective as those in your jurisdiction. If you&rsquo;re located outside the United States and choose to provide your PII to us, we may transfer your PII to the United States and process it there. Your consent to this Privacy Policy followed by your submission of any PII represents your agreement to that transfer.</span></p>
<h3 dir="ltr"><span>Our Policy Toward Children.</span></h3>
<p dir="ltr"><span>Our Services are not directed to children under 13 and we do not knowingly collect PII from children under 13. If we learn that we have collected PII of a child under 13 we will take steps to delete such information from our files as soon as possible.</span></p>
<h3 dir="ltr"><span>Changes to Privacy Policy.</span></h3>
<p dir="ltr"><span>Any information that we collect is subject to the privacy policy in effect at the time such information is collected. We may, however, modify and revise this Privacy Policy from time to time. If we make any material changes to this Privacy Policy, we&rsquo;ll notify you of such changes by posting them on the Services or by sending you an email or other notification, and we&rsquo;ll indicate when such changes will become effective.</span></p>
<h3 dir="ltr"><span>Questions?</span></h3>
<p dir="ltr"><span>Please contact us at </span><a href="mailto:founders@nomful.com"><span>founders@nomful.com</span></a><span> if you have any questions about our Privacy Policy.</span></p>
      
</div>
<?php include 'footer.php';?>
