<?php include 'header.php';?>
<div class="row">
  <p dir="ltr"><span>Nomful Customer Terms of Service</span></p>
<p dir="ltr"><span>Last Updated: 8/12/2014</span></p>
<p dir="ltr"><span>Welcome to the Nomful (&ldquo;Nomful,&rdquo; &ldquo;we&rdquo; or &ldquo;us&rdquo;) mobile device application (&ldquo;App&rdquo;) and website located at Nomful.us (the &ldquo;Site&rdquo;). Please read these Terms of Service (the &ldquo;Terms&rdquo;) carefully because they govern your use of our App and Site and the nutritional information and services accessible via our App. To make these Terms easier to read, the Site and our platform and services and App are collectively called the &ldquo;Services.&rdquo;</span></p>
<h3 dir="ltr"><span>Agreement to Terms</span></h3>
<p dir="ltr"><span>By using our Services, you agree to be bound by these Terms and by our Privacy Policy. If you don&rsquo;t agree to these Terms and our Privacy Policy, do not use the Services. * Changes to Terms or Services*</span></p>
<p dir="ltr"><span>We may modify the Terms at any time, in our sole discretion. If we do so, we&rsquo;ll let you know either by posting the modified Terms on the Site or App or through other communications. It&rsquo;s important that you review the Terms whenever we modify them because if you continue to use the Services after we have posted modified Terms on the Site or App, you are indicating to us that you agree to be bound by the modified Terms. If you don&rsquo;t agree to be bound by the modified Terms, then you can&rsquo;t use the Services anymore. Because our Services are evolving over time we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.</span></p>
<h3 dir="ltr"><span>Who May Use the Services</span></h3>
<p dir="ltr"><span>Eligibility</span></p>
<p dir="ltr"><span>You may use the Services only if you are 18 years or older and capable of forming a binding contract with Nomful and are not barred from using the Services under applicable law.</span></p>
<h3 dir="ltr"><span>Registration and Your Information</span></h3>
<p dir="ltr"><span>If you want to access and use the Services, you&rsquo;ll have to create an account (&ldquo;Account&rdquo;). You can do this via the App or our website.</span></p>
<p dir="ltr"><span>It&rsquo;s important that you provide us with accurate, complete and up-to-date information for your Account and you agree to update such information to keep it accurate, complete and up-to-date. If you don&rsquo;t, we might have to suspend or terminate your Account. You agree that you won&rsquo;t disclose your Account password to anyone and you&rsquo;ll notify us immediately of any unauthorized use of your Account. You&rsquo;re responsible for all activities that occur under your Account, whether or not you know about them.</span></p>
<h3 dir="ltr"><span>The Services </span></h3>
<p dir="ltr"><span>Through the Services, we provide nutritional information services including:</span></p>
<ul>
<li dir="ltr">
<p dir="ltr"><span>The ability to select a nutrition expert offered by Nomful for the provision of nutritional information (each, a &ldquo;Coach&rdquo;).</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Customized nutritional information from your Coach based on information about your diet that you provide to us and your Coach through the Services;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Goal-oriented feedback from your Coach as you progress towards your fitness or nutritional goals.</span></p>
</li>
</ul>
<p><span><span>&nbsp;</span></span></p>
<p dir="ltr"><span>The Coaches assigned to you upon registration of your Account in the App are based on information about your fitness or nutritional goals and other information that you provide to us when registering your Account. While Nomful presents these Coaches for your selection, you assume full responsibility for your Coach selection and for choosing the Coach best suited to your goals. If you would like to change your Coach, please contact Nomful at founders@nomful.com. Nomful reserves the right to change your Coach at any time, for any reason.</span></p>
<p dir="ltr"><span>Nomful endeavors to ensure positive interactions between you and your Coach; however, Nomful makes no representations about the suitability, reliability, or accuracy of the Coaches&rsquo; nutritional advice. Nomful may monitor the provision of the Services to ensure the quality of interactions with your Coach.</span></p>
<p dir="ltr"><span>Because our Coaches are real human beings, they may become unavailable to respond to you and provide information through the Services from time to time.</span></p>
<h3 dir="ltr"><span>Payment Terms</span></h3>
<p dir="ltr"><span>You agree to pay, and authorize Nomful&rsquo;s third party payment processor to charge using your selected payment method, for all applicable fees and taxes that may accrue in relation to your subscription to use the Services. The fees for your subscription to use the Services are set forth at nomful.com/pricing. All fees are non-refundable except as required by law. You are responsible for providing complete and accurate billing and contact information to us. We may suspend or terminate the Services if fees are 30 days past due. Unless otherwise specified in the payment terms set forth at nomful.com/pricing, all fees are payable in advance on either a weekly or a monthly basis (at your discretion) and will accrue on a rolling basis from your date of Account registration (for example, under a monthly billing plan, if you register your Account on the 15th day of the month, you will be billed at the time of registration and on approximately the 15th day of each month thereafter; under a weekly billing plan, if you register your Account on a Monday, you will be billed at the time of registration and on each Monday thereafter. If you want to terminate your subscription to the Services, you must notify us of this fact by founders@nomful.com and you will no longer be charged the monthly fee starting in the month immediately after the month in which you provided your notice of termination. You will not be refunded for any partial month&rsquo;s subscription to use the Services. We may revise the fees for the Services by providing you at least 30 days prior notice on the Site.</span></p>
<h3 dir="ltr"><span>Feedback</span></h3>
<p dir="ltr"><span>We welcome feedback, comments and suggestions for improvements to the Services (&ldquo;Feedback&rdquo;). You can submit Feedback by emailing us at founders@nomful.com. You grant to us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicensable and transferable license under any and all intellectual property rights that you own or control to use, copy, modify, create derivative works based upon and otherwise exploit the Feedback for any purpose.</span></p>
<h3 dir="ltr"><span>Privacy Policy</span></h3>
<p dir="ltr"><span>Please refer to our </span><a href="http://rise.us/privacy-policy"><span>Privacy Policy</span></a><span> for information on how we collect, use and disclose information from our users.</span></p>
<h3 dir="ltr"><span>Content and Content Rights</span></h3>
<p dir="ltr"><span>For purposes of these Terms: (i) &ldquo;Content&rdquo; means text, graphics, images, music, software, audio, video, works of authorship of any kind, and information or other materials that are posted, generated, provided or otherwise made available through the Services; and (ii) &ldquo;User Content&rdquo; means any Content that Account holders (including you) provide to be made available through the Services. Content includes without limitation User Content.</span></p>
<h3 dir="ltr"><span>Content Ownership, Responsibility and Removal</span></h3>
<p dir="ltr"><span>Nomful does not claim any ownership rights in any User Content that you make available through the Services and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit your User Content. Subject to the foregoing, Nomful and its licensors exclusively own all right, title and interest in and to the Services and Content, including all associated intellectual property rights. You acknowledge that the Services and Content are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Services.</span></p>
<h3 dir="ltr"><span>Rights in User Content Granted by You</span></h3>
<p dir="ltr"><span>By making any User Content available through Services you hereby grant to Nomful a non-exclusive, transferable, sublicenseable, worldwide, royalty-free license to use, copy, modify, create derivative works based upon, distribute, publicly display, publicly perform and distribute your User Content in connection with operating and providing the Services and Content to you and to other Account holders.</span></p>
<p dir="ltr"><span>You are solely responsible for all your User Content. You represent and warrant that you own all your User Content or you have all rights that are necessary to grant us the license rights in your User Content under these Terms. You also represent and warrant that neither your User Content, nor your use and provision of your User Content to be made available through the Services, nor any use of your User Content by Nomful on or through the Services will infringe, misappropriate or violate a third party&rsquo;s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</span></p>
<p dir="ltr"><span>You can remove your User Content by specifically deleting it. However, in certain instances, some of your User Content may not be completely removed and copies of your User Content may continue to exist on the Services. We are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any of your User Content.</span></p>
<h3 dir="ltr"><span>Rights in Content Granted by Nomful</span></h3>
<p dir="ltr"><span>Subject to your compliance with these Terms, Nomful grants you a limited, non-exclusive, non-transferable, non-sublicenseable license to download, view, copy and display the Content solely in connection with your permitted use of the Services and solely for your personal and non-commercial purposes.</span></p>
<h3 dir="ltr"><span>Rights and Terms for Apps</span></h3>
<p dir="ltr"><span>Rights in App Granted by Nomful</span></p>
<p dir="ltr"><span>Subject to your compliance with these Terms, Nomful grants you a limited non-exclusive, non-transferable, non-sublicensable license to download and install a copy of the App on a mobile device that you own or control and to run such copy of the App solely for your own personal non-commercial purposes. Nomful reserves all rights in and to the App not expressly granted to you under these Terms.</span></p>
<h3 dir="ltr"><span>Additional Terms for App Store Apps</span></h3>
<p dir="ltr"><span>If you download the App through or from any app store or distribution platform (like the Apple App Store or Google Play) where the App is made available (each, an &ldquo;App Provider&rdquo;), then you acknowledge and agree that:</span></p>
<ul>
<li dir="ltr">
<p dir="ltr"><span>These Terms are concluded between you and Nomful, and not with the App Provider, and that Nomful (not the App Provider), is solely responsible for the App.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>The App Provider has no obligation to furnish any maintenance and support services with respect to the App.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>In the event of any failure of the App to conform to any applicable warranty, you may notify the App Provider, and the App Provider will refund the purchase price for the App to you (if applicable) and to the maximum extent permitted by applicable law, the App Provider will have no other warranty obligation whatsoever with respect to the App. Any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of Nomful.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>The App Provider is not responsible for addressing any claims you have or any claims of any third party relating to the App or your possession and use of the App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>In the event of any third party claim that the App or your possession and use of that App infringes that third party&rsquo;s intellectual property rights, Nomful will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by these Terms.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>The App Provider and its subsidiaries are third party beneficiaries of these Terms as related to your license of the App, and that, upon your acceptance of the terms and conditions of these Terms, the App Provider will have the right (and will be deemed to have accepted the right) to enforce these Terms as related to your license of the App against you as a third party beneficiary thereof.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>You must also comply with all applicable third party terms of service when using the App.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>You agree to comply with all U.S. and foreign export laws and regulations to ensure that neither the App nor any technical data related thereto nor any direct product thereof is exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations. By using the App you represent and warrant that: (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a &ldquo;terrorist supporting&rdquo; country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.</span></p>
</li>
</ul>
<p dir="ltr"><span>You may not: (i) copy, modify or create derivative works based on the App; (ii) distribute, transfer, sublicense, lease, lend or rent the App to any third party; (iii) reverse engineer, decompile or disassemble the App; or (iv) make the functionality of the App available to multiple users through any means.</span></p>
<h3 dir="ltr"><span>General Prohibitions and Nomful&rsquo; Enforcement Rights</span></h3>
<p dir="ltr"><span>You agree not to do any of the following:</span></p>
<ul>
<li dir="ltr">
<p dir="ltr"><span>Post, upload, publish, submit or transmit any Content that: (i) infringes, misappropriates or violates a third party&rsquo;s patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any person or entity; or (vii) promotes illegal or harmful activities or substances.</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Use, display, mirror or frame the Services, or any individual element within the Services, Nomful&rsquo;s name, any Nomful trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page or in the App, without Nomful&rsquo;s express written consent;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Access, tamper with, or use non-public areas of the Services, Nomful&rsquo;s computer systems, or the technical delivery systems of Nomful&rsquo;s providers;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Attempt to probe, scan, or test the vulnerability of any Nomful system or network or breach any security or authentication measures;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Avoid, bypass, remove, deactivate, impair, descramble or otherwise circumvent any technological measure implemented by Nomful or any of Nomful&rsquo;s providers or any other third party (including another user) to protect the Services or Content;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Attempt to access or search the Services or Content or download Content from the Services through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers, data mining tools or the like) other than the software and/or search agents provided by Nomful or other generally available third party web browsers;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters or other form of solicitation;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Use any meta tags or other hidden text or metadata utilizing a Nomful trademark, logo URL or product name without Nomful&rsquo;s express written consent;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Use the Services or Content for any commercial purpose or for the benefit of any third party or in any manner not permitted by these Terms;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Services or Content to send altered, deceptive or false source-identifying information;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Services or Content;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Interfere with, or attempt to interfere with, the access of any user, host or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Services;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Collect or store any personally identifiable information from the Services from other users of the Services without their express permission;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Impersonate or misrepresent your affiliation with any person or entity;</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Violate any applicable law or regulation; or</span></p>
</li>
<li dir="ltr">
<p dir="ltr"><span>Encourage or enable any other individual to do any of the foregoing.</span></p>
</li>
</ul>
<p dir="ltr"><span>Although we&rsquo;re not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms, or to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any Content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</span></p>
<h3 dir="ltr"><span>Links to Third Party Websites or Resources</span></h3>
<p dir="ltr"><span>The Services may contain links to third-party websites or resources. We provide these links only as a convenience and are not responsible for the content, products or services on or available from those websites or resources or links displayed on such sites. You acknowledge sole responsibility for, and assume all risk arising from, your use of any third-party websites or resources. * DMCA/Copyright Policy*</span></p>
<p dir="ltr"><span>Nomful respects copyright law and expects its users to do the same. It is Nomful&rsquo;s policy to terminate in appropriate circumstances Account holders who repeatedly infringe the rights of copyright holders. Please see Nomful&rsquo;s Copyright Policy at nomful.com for further information.</span></p>
<h3 dir="ltr"><span>Termination</span></h3>
<p dir="ltr"><span>We may terminate your access to and use of the Services, at our sole discretion, at any time and without notice to you. You may cancel your Account at any time by sending an email to us at founders@nomful.com . Upon any termination, discontinuation or cancellation of Services or your Account, all provisions of these Terms which by their nature should survive will survive, including, without limitation, ownership provisions, warranty and professional/medical services disclaimers, assumption of risk and indemnity, limitations of liability, and dispute resolution provisions.</span></p>
<h3 dir="ltr"><span>Warranty Disclaimers</span></h3>
<p dir="ltr"><span>THE SERVICES AND CONTENT ARE PROVIDED &ldquo;AS IS,&rdquo; WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. We make no warranty that the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness or reliability of any Content.</span></p>
<h3 dir="ltr"><span>No Professional Services or Advice; No Doctor-Patient Relationship</span></h3>
<p dir="ltr"><span>Nomful provides the Services for informational purposes only. We provide a platform so that a Coach may provide you with nutritional information relating to your fitness, weight loss and/or nutritional goals; however, you acknowledge that Nomful is not a fitness, weight loss, registered dietitian or certified nutritionist, medical professional or certified personal trainer. THE SERVICES DO NOT CONTAIN OR CONSTITUTE, AND SHOULD NOT BE INTERPRETED AS, PROFESSIONAL OR MEDICAL ADVICE OR OPINION OF ANY KIND AND THE SERVICES ARE NOT A SUBSTITUTE FOR PROFESSIONAL OR MEDICAL ADVICE OR OPINION OF ANY KIND. THE INFORMATION MADE AVAILABLE ON OR THROUGH THE SERVICES SHOULD NOT BE RELIED UPON WHEN MAKING MEDICAL DECISIONS, OR TO DIAGNOSE OR TREAT A MEDICAL OR HEALTH CONDITION. YOUR USE OF THE SERVICES DOES NOT CREATE A DOCTOR-PATIENT RELATIONSHIP BETWEEN YOU AND NOMFUL.</span></p>
<p dir="ltr"><span>YOU HEREBY AGREE THAT, BEFORE USING THE SERVICES, YOU WILL CONSULT YOUR PHYSICIAN, PARTICULARLY IF YOU ARE AT RISK FOR PROBLEMS RESULTING FROM CHANGES IN YOUR DIET OR LIFESTYLE. In becoming a user of the Services, you affirm that a physician has specifically approved your use of the Services. The Services are intended for use only by individuals healthy enough to make changes to their diets and lifestyles, and are not intended for use by minors or individuals with any type of health condition that makes the kind of changes to diet or lifestyle suggested by the Services unsafe or inappropriate. You should discontinue diet or other lifestyle changes in cases where such changes cause pain or severe discomfort, and should consult a medical expert prior to returning to diet or other lifestyle changes in such cases. We reserve the right to deny you access to the Services for any reason or no reason, including if we determine, in our sole discretion, that you have certain medical conditions.</span></p>
<h3 dir="ltr"><span>Assumption of Risk and Indemnity</span></h3>
<p dir="ltr"><span>Using the Services involves the risk of physical or mental injury or illness. Specific risks vary from one diet or lifestyle change to another and the risks range from minor injuries or illness to major injuries or illness, such as catastrophic injuries including death. IN CONSIDERATION OF YOUR USE OF THE SERVICES, YOU UNDERSTAND AND VOLUNTARILY ACCEPT THIS RISK AND AGREE THAT NOMFUL, ITS OFFICERS, DIRECTORS, EMPLOYEES, CONSULTANTS, AGENTS, SUCCESSORS AND ASSIGNS WILL NOT BE LIABLE FOR ANY INJURY, INCLUDING, WITHOUT LIMITATION, PERSONAL, BODILY, OR MENTAL INJURY, ECONOMIC LOSS OR ANY DAMAGE TO YOU, YOUR SPOUSE, UNBORN CHILD, OR RELATIVES RESULTING FROM YOUR USE OF THE SERVICES, INCLUDING, BUT NOT LIMITED TO, THE NEGLIGENCE OF NOMFUL OR ANYONE ON NOMFUL&rsquo;S BEHALF. YOU UNDERSTAND AND ACKNOWLEDGE THAT NOMFUL IS PROVIDING INFORMATIONAL SERVICES ONLY AND MAY NOT BE HELD LIABLE FOR DEFECTIVE PRODUCTS.</span></p>
<p dir="ltr"><span>YOU KNOWINGLY AND FREELY ASSUME ALL RISK WHEN USING THE SERVICES. YOU, ON BEHALF OF YOURSELF, YOUR PERSONAL REPRESENTATIVES AND YOUR HEIRS, HEREBY VOLUNTARILY AGREE TO RELEASE, WAIVE, DISCHARGE, HOLD HARMLESS, DEFEND AND INDEMNIFY NOMFUL AND ITS OFFICERS, DIRECTORS, EMPLOYEES, CONSULTANTS, AGENTS, SUCCESSORS AND ASSIGNS, FROM AND AGAINST ANY CLAIMS, DISPUTES, DEMANDS, LIABILITIES, DAMAGES, LOSSES, AND COSTS AND EXPENSES, INCLUDING, WITHOUT LIMITATION, REASONABLE LEGAL AND ACCOUNTING FEES ARISING OUT OF OR IN ANY WAY CONNECTED WITH (I) YOUR ACCESS TO OR USE OF THE SERVICES OR CONTENT OR (II) YOUR VIOLATION OF THESE TERMS, INCLUDING, WITHOUT LIMITATION, FOR BODILY INJURY, WRONGFUL DEATH, EMOTIONAL DISTRESS, LOSS OF SERVICES OR OTHER DAMAGES OR HARM, WHETHER TO YOU OR TO THIRD PARTIES, WHICH MAY RESULT FROM YOUR USE OF THE SERVICES.</span></p>
<h3 dir="ltr"><span>Limitation of Liability</span></h3>
<p dir="ltr"><span>NEITHER NOMFUL NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES OR CONTENT WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE SERVICES ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES OR CONTENT, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT NOMFUL HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU.</span></p>
<p dir="ltr"><span>IN NO EVENT WILL NOMFUL&rsquo;S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES OR CONTENT EXCEED THE AMOUNTS YOU HAVE PAID TO NOMFUL FOR USE OF THE SERVICES.</span></p>
<p dir="ltr"><span>THE ASSUMPTION OF RISK AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN NOMFUL AND YOU.</span></p>
<h3 dir="ltr"><span>Dispute Resolution</span></h3>
<p dir="ltr"><span>Governing Law</span></p>
<p dir="ltr"><span>These Terms and any action related thereto will be governed by the laws of the State of Deleware without regard to its conflict of laws provisions.</span></p>
<h3 dir="ltr"><span>Agreement to Arbitrate</span></h3>
<p dir="ltr"><span>You and Nomful agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation or validity thereof or the use of the Services or Content (collectively, &ldquo;Disputes&rdquo;) will be settled by binding arbitration, except that each party retains the right: (i) to bring an individual action in small claims court and (ii) to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party&rsquo;s copyrights, trademarks, trade secrets, patents or other intellectual property rights (the action described in the foregoing clause (ii), an &ldquo;IP Protection Action&rdquo;). The exclusive jurisdiction and venue of any IP Protection Action will be the state and federal courts located in the Northern District of California and each of the parties hereto waives any objection to jurisdiction and venue in such courts. You acknowledge and agree that you and Nomful are each waiving the right to a trial by jury or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and Nomful otherwise agree in writing, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this &ldquo;Dispute Resolution&rdquo; section will be deemed void. Except as provided in the preceding sentence, this &ldquo;Dispute Resolution&rdquo; section will survive any termination of these Terms.</span></p>
<h3 dir="ltr"><span>Arbitration Rules</span></h3>
<p dir="ltr"><span>The arbitration will be administered by the American Arbitration Association (&ldquo;AAA&rdquo;) in accordance with the Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes (the &ldquo;AAA Rules&rdquo;) then in effect, except as modified by this &ldquo;Dispute Resolution&rdquo; section. (The AAA Rules are available at </span><a href="https://www.adr.org/aaa/faces/services/disputeresolutionservices/arbitration"><span>www.adr.org/arb_med</span></a><span> or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.</span></p>
<p dir="ltr"><span>* Arbitration Process*</span></p>
<p dir="ltr"><span>A party who desires to initiate arbitration must provide the other party with a written Demand for Arbitration as specified in the AAA Rules. (The AAA provides a form </span><a href="https://www.adr.org/aaa/ShowPDF?doc=ADRSTG_004175"><span>Demand for Arbitration</span></a><span> and a </span><a href="https://www.adr.org/aaa/ShowPDF?doc=ADRSTG_015822"><span>separate form for California residents</span></a><span>.) The arbitrator will be either a retired judge or an attorney licensed to practice law and will be selected by the parties from the AAA&rsquo;s roster of arbitrators. If the parties are unable to agree upon an arbitrator within seven (7) days of delivery of the Demand for Arbitration, then the AAA will appoint the arbitrator in accordance with the AAA Rules.</span></p>
<h3 dir="ltr"><span>Arbitration Location and Procedure</span></h3>
<p dir="ltr"><span>Unless you and Nomful otherwise agree, the arbitration will be conducted in the county where you reside. If your claim does not exceed $10,000, then the arbitration will be conducted solely on the basis of the documents that you and Nomful submit to the arbitrator, unless you request a hearing or the arbitrator determines that a hearing is necessary. If your claim exceeds $10,000, your right to a hearing will be determined by the AAA Rules. Subject to the AAA Rules, the arbitrator will have the discretion to direct a reasonable exchange of information by the parties, consistent with the expedited nature of the arbitration.</span></p>
<h3 dir="ltr"><span>Arbitrator&rsquo;s Decision</span></h3>
<p dir="ltr"><span>The arbitrator will render an award within the time frame specified in the AAA Rules. The arbitrator&rsquo;s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court having jurisdiction thereof. The arbitrator&rsquo;s award of damages must be consistent with the terms of the &ldquo;Limitation of Liability&rdquo; section above as to the types and amounts of damages for which a party may be held liable. The arbitrator may award declaratory or injunctive relief only in favor of the claimant and only to the extent necessary to provide relief warranted by the claimant&rsquo;s individual claim. If you prevail in arbitration you will be entitled to an award of attorneys&rsquo; fees and expenses, to the extent provided under applicable law. Nomful will not seek, and hereby waives all rights it may have under applicable law to recover, attorneys&rsquo; fees and expenses if it prevails in arbitration.</span></p>
<h3 dir="ltr"><span>Fees</span></h3>
<p dir="ltr"><span>Your responsibility to pay any AAA filing, administrative and arbitrator fees will be solely as set forth in the AAA Rules. However, if your claim for damages does not exceed $75,000, Nomful will pay all such fees unless the arbitrator finds that either the substance of your claim or the relief sought in your Demand for Arbitration was frivolous or was brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)). * Changes*</span></p>
<p dir="ltr"><span>Notwithstanding the provisions of the &ldquo;Changes to Terms or Services&rdquo; section above, if Nomful changes this &ldquo;Dispute Resolution&rdquo; section after the date you first accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email to founders@nomful.com within 30 days of the date such change became effective, as indicated in the &ldquo;Last Updated&rdquo; date above or in the date of Nomful&rsquo;s email to you notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and Nomful in accordance with the provisions of this &ldquo;Dispute Resolution&rdquo; section as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).</span></p>
<h3 dir="ltr"><span>General Terms</span></h3>
<p dir="ltr"><span>These Terms constitute the entire and exclusive understanding and agreement between Nomful and you regarding the Services and Content, and these Terms supersede and replace any and all prior oral or written understandings or agreements between Nomful and you regarding the Services and Content. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.</span></p>
<p dir="ltr"><span>You may not assign or transfer these Terms, by operation of law or otherwise, without Nomful&rsquo;s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. Nomful may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.</span></p>
<p dir="ltr"><span>Any notices or other communications provided by Nomful under these Terms, including those regarding modifications to these Terms, will be given: by Nomful (i) via email; or (ii) by posting to the Services. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.</span></p>
<p dir="ltr"><span>Nomful&rsquo;s failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Nomful. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</span></p>
<h3 dir="ltr"><span>Contact Information</span></h3>
<p dir="ltr"><span>If you have any questions about these Terms or the Services, please contact Nomful at founders@nomful.com.</span></p>
<p><span>&nbsp;</span></p>
    
</div>
<?php include 'footer.php';?>
